version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ESM-scraping-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-y66anb5193ur"
s3_prefix = "ESM-scraping-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
