AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ESMScraping

  SAM Template for ESMScraping

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  ESMScrapingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "ESM_Scraping"
      CodeUri: ./esm_scraping
      Handler: app.lambda_handler
      Runtime: python3.7
      Architectures:
        - x86_64
      Layers:
        - !Ref MyLayer
      Events:
        ESMScraping:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /base
            Method: get
      MemorySize: 512
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: MyLayer description
      ContentUri: ./layers/
      CompatibleRuntimes:
        - python3.7
      LayerName: "ESM-scraping-packages"
    Metadata:
      BuildMethod: python3.7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ESMScrapingApi:
    Description: "API Gateway endpoint URL for Prod stage for ESMScraping function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/base/"
  ESMScrapingFunction:
    Description: "ESM Scraping lambda Function ARN"
    Value: !GetAtt ESMScrapingFunction.Arn
  ESMScrapingFunctionIamRole:
    Description: "Implicit IAM Role created for lambda function"
    Value: !GetAtt ESMScrapingFunctionRole.Arn
